export const ADD_NEW_METAL_START = "ADD_NEW_METAL_START";
export const ADD_NEW_METAL_SUCCESS = "ADD_NEW_METAL_SUCCESS";
export const ADD_NEW_METAL_FAILED = "ADD_NEW_METAL_FAILED";

export const VIEW_ALL_METAL_START = "VIEW_ALL_METAL_START";
export const VIEW_ALL_METAL_SUCCESS = "VIEW_ALL_METAL_SUCCESS";
export const VIEW_ALL_METAL_FAILED = "VIEW_ALL_METAL_FAILED";

export const METAL_STATE = "METAL_STATE";
export const PRODUCT_STATE = "PRODUCT_STATE";

export const GET_METAL_LIST_START = "GET_METAL_LIST_START";
export const GET_METAL_LIST_SUCCESS = "GET_METAL_LIST_SUCCESS";
export const GET_METAL_LIST_FAILED = "GET_METAL_LIST_FAILED";

export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";
