export const ADD_NEW_METAL_START = "ADD_NEW_METAL_START";
export const ADD_NEW_METAL_SUCCESS = "ADD_NEW_METAL_SUCCESS";
export const ADD_NEW_METAL_FAILED = "ADD_NEW_METAL_FAILED";

export const VIEW_ALL_METAL_START = "VIEW_ALL_METAL_START";
export const VIEW_ALL_METAL_SUCCESS = "VIEW_ALL_METAL_SUCCESS";
export const VIEW_ALL_METAL_FAILED = "VIEW_ALL_METAL_FAILED";

export const METAL_STATE = "METAL_STATE";
export const PRODUCT_STATE = "PRODUCT_STATE";

export const GET_METAL_LIST_START = "GET_METAL_LIST_START";
export const GET_METAL_LIST_SUCCESS = "GET_METAL_LIST_SUCCESS";
export const GET_METAL_LIST_FAILED = "GET_METAL_LIST_FAILED";

export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const GET_ALL_PRODUCT_START = "GET_ALL_PRODUCT_START";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAILED = "GET_ALL_PRODUCT_FAILED";

export const GET_CUSTOMER_BY_NUMBER_FOR_SALE_START =
  "GET_CUSTOMER_BY_NUMBER_FOR_SALE_START";
export const GET_CUSTOMER_BY_NUMBER_FOR_SALE_SUCCESS =
  "GET_CUSTOMER_BY_NUMBER_FOR_SALE_SUCCESS";
export const GET_CUSTOMER_BY_NUMBER_FOR_SALE_FAILED =
  "GET_CUSTOMER_BY_NUMBER_FOR_SALE_FAILED";

export const ADD_NEW_CUSTOMER_START = "ADD_NEW_CUSTOMER_START";
export const ADD_NEW_CUSTOMER_SUCCESS = "ADD_NEW_CUSTOMER_SUCCESS";
export const ADD_NEW_CUSTOMER_FAILED = "ADD_NEW_CUSTOMER_FAILED";

export const GET_PRODUCT_BY_TAG_START = "GET_PRODUCT_BY_TAG_START";
export const GET_PRODUCT_BY_TAG_SUCCESS = "GET_PRODUCT_BY_TAG_SUCCESS";
export const GET_PRODUCT_BY_TAG_FAILED = "GET_PRODUCT_BY_TAG_FAILED";

export const GENRATE_BILL_START = "GENRATE_BILL_START";
export const GENRATE_BILL_SUCCESS = "GENRATE_BILL_SUCCESS";
export const GENRATE_BILL_FAILED = "GENRATE_BILL_FAILED";
